Repository AvaniMuchhala/adventure-architect, pull requests merged in 2023-03, with the labels that each got.

#2 Feature: Building Models
  server/models/Hotel.js
  server/models/Transportation.js
  server/models/Trip.js
  server/models/User.js
Labels: new feature

#1 Tailwind
  client/package.json
  client/src/App.js
  client/src/assets/plane.svg
  client/src/components/Nav/Nav.js
  client/src/index.css
  client/src/index.js
  client/src/pages/Home.js
  client/tailwind.config.js
Labels: new feature

#4 Login & Signup pages created
  client/package.json
  client/src/App.js
  client/src/assets/plane.svg
  client/src/components/Nav/Nav.js
  client/src/index.css
  client/src/pages/Login.js
  client/src/pages/Profile.js
  client/src/pages/Signup.js
  client/tailwind.config.js
Labels: new feature

#9 Feature/type defs layne
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#6 Feature/form submission functionality
  client/src/pages/Login.js
  client/src/pages/Signup.js
Labels: new feature

#10 Dark Theme
  client/public/index.html
  client/src/App.js
  client/src/components/Nav/Nav.js
  client/src/index.css
  client/src/pages/Dashboard.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
  client/tailwind.config.js
Labels: enhancement, new feature

#14 Feature/calender
  client/package.json
  client/src/App.js
  client/src/components/Nav/Nav.js
  client/src/index.css
  client/src/pages/Calendar.js
  client/src/pages/Dashboard.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
  client/src/utils/event-utils.js
Labels: new feature
